### ISSUE TITLE
Wahrnehmung/Zugang zu den Seminapparaten für die Studierenden verbessern

### ISSUE THREAD

**Issue by msievers** [ubpb/semapp2#2]
Es gibt Defizite bei der Wahrnehmung bzw. dem Auffinden der (e)Seminarapparate durch die Studierenden. Folgende Szenarien können auftreten
- ein Student denkt bei dem Begriff "Seminarapparat" an ein physisches Regal, findet aber konkret keins vor, weil dieser nur im Online-Angebot existiert
- ein Student steht vor einem physischen Seminarapparat, findet aber die gesuchte Ressource nicht, weil es sich dabei um eine Ressource des (e)Seminarapparats handelt
- ein Student hat in einer Veranstaltung davon gehört, dass es einen Seminarapparat gibt, weiß aber nicht, dass diese von der Bibliothek angeboten werden und findet ihn deshalb nicht über die Webseiten der UB
### Subissues
- [ ] [Hinweise auf die Online-Seminarapparate an/in der Nähe der physischen Seminarapparate anbringen](https://github.com/ubpb/semapp2/issues/3) #3
- [ ] [Seminarappartsnamen in einem eigenen Katalog-Tab durchsuchbar machen](https://github.com/ubpb/semapp2/issues/4) #4
- [ ] [DNS Alias seminapparate.ub.uni-paderborn.de anlegen](https://github.com/ubpb/semapp2/issues/5) #5
