### ISSUE TITLE
Wunschliste gemäß Besprechung FBB vom 12.12.2013

### ISSUE THREAD

**Issue by msievers** [ubpb/semapp2#8]
- [x] [Rechtschreibfehler in Regalübersicht korrigieren](https://github.com/ubpb/semapp2/issues/7)
- [x] [Verlinkung auf Amazon aus der Detailansicht für Bücher entfernen](https://github.com/ubpb/semapp2/issues/9)
- [x] [Anzahl der Bücher für einen Seminarapparat auf 35 beschränken](https://github.com/ubpb/semapp2/issues/10)
- [x] [Freiverfasste Kommentare eines Buches bei der Übernahme in ein neues Semester mitübernehmen](https://github.com/ubpb/semapp2/issues/11)
- [x] [Ergänzung von "IMT Medien" bei "Art des Präsenzexemplars"](https://github.com/ubpb/semapp2/issues/12)
- [x] [Fachbibliotheks- und Regalnummer in der Seminarapparatsübersicht anzeigen](https://github.com/ubpb/semapp2/issues/13)
- [x] [Neu beantragte Seminarapparate zeitlich nach Eingang sortieren](https://github.com/ubpb/semapp2/issues/14)
- [x] [Entfernen der Buttons Wurde verbucht/Wurde vorgemerkt](https://github.com/ubpb/semapp2/issues/15)
- [x] [Fehler in Alephsynchronisation beim Zurückbuchen von Büchern](https://github.com/ubpb/semapp2/issues/16)
- [x] [Anzeige des tatsächlich verbuchten Exemplars für einen Seminarapparat](https://github.com/ubpb/semapp2/issues/17)
- [ ] [Zusätzliches Nachrichten-/Notizfeld im Beantragungsformular für einen Seminarapparat](https://github.com/ubpb/semapp2/issues/18)
- [ ] [Statusfeld für Buchaufträge](https://github.com/ubpb/semapp2/issues/19)
- [ ] [Internes Kommunikationssystem für Rückfragen](https://github.com/ubpb/semapp2/issues/6)
- [x] [Verbesserung der Seminarapparatsauswahl bei der Erstellung von Stellvertretern](https://github.com/ubpb/semapp2/issues/20)
- [ ] [Einführung einer neuen Vormerkungspriorität in Aleph für Stellvertretervormerkung](https://github.com/ubpb/semapp2/issues/21)
- [ ] [Möglichkeit freier Einträge in der Bücherliste](https://github.com/ubpb/semapp2/issues/22)
- [ ] [Ergänzung von Formatierungsmöglichkeiten für Bücherkommentare](https://github.com/ubpb/semapp2/issues/23)
